source 'https://rubygems.org'
ruby '3.2.0'

gem 'rails', '~> 7.1.0'
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.4'
gem 'rack-cors'
gem 'ruby-kafka', '~> 1.5'
gem 'cloudevents', '~> 1.0'
gem 'json'
gem 'dotenv-rails'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'shoulda-matchers', '~> 6.0'
end

group :development do
  gem 'listen', '~> 3.8'
end
