# orders/BUILD

load("@rules_jvm_external//:defs.bzl", "artifact")

java_import(
    name = "newrelic_files",
    jars = ["@newrelic_java//:newrelic.jar"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "artifact",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]) + ["@newrelic_java//:newrelic.yml"],  # Inclui o arquivo .yml no resources
    javacopts = ["-source", "21", "-target", "21"],
    deps = [
        "//core:artifact",
        ":newrelic_files",
        "@maven//:org_springframework_boot_spring_boot_starter",
        "@maven//:org_springframework_boot_spring_boot_starter_validation",
        "@maven//:org_springframework_boot_spring_boot_starter_oauth2_client",
        "@maven//:org_springframework_boot_spring_boot_starter_oauth2_resource_server",
        "@maven//:org_springframework_boot_spring_boot_starter_security",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jpa",
        "@maven//:org_springframework_boot_spring_boot_starter_actuator",
        "@maven//:org_springframework_boot_spring_boot_starter_cache",
        "@maven//:org_springframework_boot_spring_boot_starter_data_redis",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_mongodb_mongodb_driver_sync",
        "@maven//:org_liquibase_liquibase_core",
        "@maven//:org_liquibase_ext_liquibase_mongodb",
        "@maven//:io_grpc_grpc_netty",
        "@maven//:io_grpc_grpc_netty_shaded",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
    ],
)

java_test(
    name = "unit",
    srcs = glob(["src/test/java/**/*.java"]),
    deps = [
        ":artifact",
        "@maven//:org_testcontainers_kafka",
        "@maven//:org_testcontainers_mongodb",
        "@maven//:io_grpc_grpc_testing",
        "@maven//:org_mockito_mockito_inline",
    ],
)