load("@rules_jvm_external//:defs.bzl", "artifact")
load("@openapi_tools_generator_bazel//:defs.bzl", "openapi_generator")

# Importa o New Relic como biblioteca Java
java_import(
    name = "newrelic",
    jars = ["@newrelic_java//:newrelic.jar"],
    visibility = ["//visibility:public"],
)

# Gera o código a partir do OpenAPI
openapi_generator(
    name = "orders_api_codegen",
    spec = "src/main/resources/oas/orders-api.yaml",
    generator = "spring",
    config = "config.yml",
)

# Cópia dos arquivos gerados para o diretório apropriado
genrule(
    name = "copy_orders_api",
    srcs = [":orders_api_codegen"],
    outs = ["generated_orders_api/com/gabriel/specs/orders/OrdersApi.java"],  # Especifique um arquivo de saída
    cmd = """
    rm -rf $(OUTS) && mkdir -p $(dirname $(OUTS)) && cp -r $(SRCS)/* $(dirname $(OUTS))
    """,
    visibility = ["//visibility:public"],
)

# Define a biblioteca Java com o código gerado
java_library(
    name = "orders_api",
    srcs = glob(["generated_orders_api/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [":copy_orders_api"],  # Adiciona a dependência para garantir a cópia
    runtime_deps = [
        "@maven//:org_springframework_boot_spring_boot_starter",
        "@maven//:org_springframework_boot_spring_boot_starter_web"
    ],
)

# Define a biblioteca principal que depende do orders_api
java_library(
    name = "artifact",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]) + ["@newrelic_java//:newrelic.yml"],
    javacopts = ["-source", "21", "-target", "21"],
    deps = [
        "//core:artifact",
        ":newrelic",
        ":orders_api",
        "@maven//:org_springframework_boot_spring_boot_starter",
        "@maven//:org_springframework_boot_spring_boot_starter_validation",
        "@maven//:org_springframework_boot_spring_boot_starter_oauth2_client",
        "@maven//:org_springframework_boot_spring_boot_starter_oauth2_resource_server",
        "@maven//:org_springframework_boot_spring_boot_starter_security",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jpa",
        "@maven//:org_springframework_boot_spring_boot_starter_actuator",
        "@maven//:org_springframework_boot_spring_boot_starter_cache",
        "@maven//:org_springframework_boot_spring_boot_starter_data_redis",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_mongodb_mongodb_driver_sync",
        "@maven//:org_liquibase_liquibase_core",
        "@maven//:org_liquibase_ext_liquibase_mongodb",
        "@maven//:io_grpc_grpc_netty",
        "@maven//:io_grpc_grpc_netty_shaded",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
    ],
)

# Configuração para testes unitários
java_test(
    name = "unit",
    srcs = glob(["src/test/java/**/*.java"]),
    deps = [
        ":artifact",
        "@maven//:org_testcontainers_kafka",
        "@maven//:org_testcontainers_mongodb",
        "@maven//:io_grpc_grpc_testing",
        "@maven//:org_mockito_mockito_inline",
    ],
)