load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS", "java_test_suite")
load("@openapi_tools_generator_bazel//:defs.bzl", "openapi_generator")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_spring//springboot:springboot.bzl", "springboot")

java_import(
    name = "newrelic",
    jars = ["@newrelic_java//:newrelic.jar"],
    visibility = ["//visibility:public"],
)

openapi_generator(
    name = "orders_api_files",
    config = "config.yml",
    generator = "spring",
    spec = "src/main/resources/oas/orders-api.yaml",
)

genrule(
    name = "orders_api_jar",
    srcs = [":orders_api_files"],
    outs = ["orders_api.srcjar"],
    cmd = """
    files=$$(find -L $(location :orders_api_files)/src/main/java -type f)
    zipper_args=()
    for f in $${files[@]}; do
    path_in_zip="$${f/bazel-out\\/k8-fastbuild\\/bin\\/orders_api_files\\/src\\/main\\/java\\//}"
    zipper_args+=("$$path_in_zip=$$f")
    done
    $(location @bazel_tools//tools/zip:zipper) c $@ $${zipper_args[@]}
    """,
    tools = ["@bazel_tools//tools/zip:zipper"],
)

java_library(
    name = "orders_api",
    srcs = [":orders_api.srcjar"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:jakarta_annotation_jakarta_annotation_api",
        "@maven//:jakarta_validation_jakarta_validation_api",
        "@maven//:org_apache_tomcat_embed_tomcat_embed_core",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_web",
    ],
)

java_library(
    name = "artifact",
    srcs = glob(["src/main/java/**/*.java"]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        ":orders_api",
        "//core:artifact",
        "//core:menu_java_grpc",
        "//core:menu_java_proto",
        "//core:permissions_java_grpc",
        "//core:permissions_java_proto",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:com_fasterxml_jackson_module_jackson_module_scala_2_13",
        "@maven//:io_cloudevents_cloudevents_api",
        "@maven//:io_cloudevents_cloudevents_core",
        "@maven//:io_cloudevents_cloudevents_json_jackson",
        "@maven//:io_cloudevents_cloudevents_kafka",
        "@maven//:io_grpc_grpc_api",
        "@maven//:io_grpc_grpc_netty",
        "@maven//:io_grpc_grpc_netty_shaded",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:io_opentelemetry_opentelemetry_exporter_otlp",
        "@maven//:io_opentelemetry_opentelemetry_sdk",
        "@maven//:io_opentelemetry_opentelemetry_sdk_trace",
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:jakarta_annotation_jakarta_annotation_api",
        "@maven//:jakarta_persistence_jakarta_persistence_api",
        "@maven//:jakarta_validation_jakarta_validation_api",
        "@maven//:javax_annotation_javax_annotation_api",
        "@maven//:org_apache_kafka_kafka_clients",
        "@maven//:org_liquibase_ext_liquibase_mongodb",
        "@maven//:org_liquibase_liquibase_core",
        "@maven//:org_mongodb_bson",
        "@maven//:org_mongodb_mongodb_driver_core",
        "@maven//:org_mongodb_mongodb_driver_sync",
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure",
        "@maven//:org_springframework_boot_spring_boot_starter_actuator",
        "@maven//:org_springframework_boot_spring_boot_starter_cache",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jpa",
        "@maven//:org_springframework_boot_spring_boot_starter_data_redis",
        "@maven//:org_springframework_boot_spring_boot_starter_oauth2_resource_server",
        "@maven//:org_springframework_boot_spring_boot_starter_security",
        "@maven//:org_springframework_boot_spring_boot_starter_validation",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
        "@maven//:org_springframework_data_spring_data_redis",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_springframework_security_spring_security_config",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_security_spring_security_oauth2_resource_server",
        "@maven//:org_springframework_security_spring_security_web",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_messaging",
        "@maven//:org_springframework_spring_tx",
        "@maven//:org_springframework_spring_web",
        "@maven//:org_springframework_spring_webmvc",
        "@maven//:org_yaml_snakeyaml",
        "@rules_spring//springboot/import_bundles:springboot_required_deps",
    ],
)

java_library(
    name = "test_utility",
    srcs = glob([
        "src/test/utils/**/*.java",
    ]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    deps = [
        ":artifact",
        ":orders_api",
        "//core:artifact",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:org_apache_tomcat_embed_tomcat_embed_core",
        "@maven//:org_jetbrains_annotations",
        "@maven//:org_springframework_data_spring_data_redis",
        "@maven//:org_springframework_security_spring_security_config",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_web",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
        "@maven//:org_testcontainers_junit_jupiter",
        "@maven//:org_testcontainers_kafka",
        "@maven//:org_testcontainers_mongodb",
        "@maven//:org_testcontainers_testcontainers",
        "@maven//:org_yaml_snakeyaml",
    ],
)

java_test_suite(
    name = "unit",
    srcs = glob([
        "src/test/unit/java/**/*.java",
    ]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob(["src/test/resources/**"]),
    runner = "junit5",
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        ":orders_api",
        ":test_utility",
        "//core:artifact",
        "//core:menu_java_grpc",
        "//core:menu_java_proto",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:io_cloudevents_cloudevents_api",
        "@maven//:io_cloudevents_cloudevents_core",
        "@maven//:io_grpc_grpc_api",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
        "@maven//:org_mongodb_bson",
        "@maven//:org_mongodb_mongodb_driver_core",
        "@maven//:org_mongodb_mongodb_driver_sync",
        "@maven//:org_springframework_data_spring_data_redis",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
    ],
)

java_test_suite(
    name = "integration",
    srcs = glob([
        "src/test/integration/java/**/*.java",
    ]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob([
        "src/test/resources/**",
    ]),
    runner = "junit5",
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        ":orders_api",
        ":test_utility",
        "//core:artifact",
        "//core:menu_java_grpc",
        "//core:menu_java_proto",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:io_cloudevents_cloudevents_api",
        "@maven//:io_cloudevents_cloudevents_core",
        "@maven//:io_grpc_grpc_api",
        "@maven//:org_apache_kafka_kafka_clients",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
        "@maven//:org_mongodb_bson",
        "@maven//:org_mongodb_mongodb_driver_core",
        "@maven//:org_mongodb_mongodb_driver_sync",
        "@maven//:org_springframework_boot_spring_boot_starter_test",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_boot_spring_boot_test_autoconfigure",
        "@maven//:org_springframework_data_spring_data_redis",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_springframework_kafka_spring_kafka_test",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_test",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
        "@maven//:org_springframework_spring_webmvc",
    ],
)

java_test_suite(
    name = "contract",
    srcs = glob([
        "src/test/contract/java/**/*.java",
    ]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob([
        "src/test/resources/**",
    ]),
    runner = "junit5",
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        ":test_utility",
        "//core:artifact",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:in_specmatic_junit5_support",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_test",
    ],
)

java_test_suite(
    name = "behavior",
    srcs = glob([
        "src/test/behavior/java/**/*.java",
    ]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob([
        "src/test/resources/**",
    ]),
    runner = "junit5",
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        ":test_utility",
        "//core:artifact",
        "//orders:orders_api",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:io_cloudevents_cloudevents_api",
        "@maven//:io_cloudevents_cloudevents_core",
        "@maven//:io_cloudevents_cloudevents_json_jackson",
        "@maven//:io_cloudevents_cloudevents_kafka",
        "@maven//:io_cucumber_cucumber_java",
        "@maven//:io_cucumber_cucumber_junit_platform_engine",
        "@maven//:io_cucumber_cucumber_spring",
        "@maven//:io_rest_assured_json_path",
        "@maven//:io_rest_assured_json_schema_validator",
        "@maven//:io_rest_assured_rest_assured",
        "@maven//:io_rest_assured_spring_mock_mvc",
        "@maven//:org_apache_kafka_kafka_clients",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_hamcrest_hamcrest",
        "@maven//:org_junit_jupiter_junit_jupiter",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_junit_jupiter_junit_jupiter_params",
        "@maven//:org_junit_platform_junit_platform_launcher",
        "@maven//:org_junit_platform_junit_platform_reporting",
        "@maven//:org_junit_platform_junit_platform_suite",
        "@maven//:org_junit_platform_junit_platform_suite_api",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_inline",
        "@maven//:org_springframework_boot_spring_boot_test",
        "@maven//:org_springframework_kafka_spring_kafka",
        "@maven//:org_springframework_kafka_spring_kafka_test",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_test",
        "@maven//:org_springframework_spring_web",
        "@maven//:org_springframework_spring_webmvc",
        "@maven//:org_testcontainers_junit_jupiter",
        "@maven//:org_testcontainers_kafka",
        "@maven//:org_testcontainers_testcontainers",
    ],
)

#java_binary(
#    name = "uber",
#    main_class = "com.gabriel.orders.OrdersApplication",
#    runtime_deps = [":artifact"],
#)

springboot(
    name = "uber",
    boot_app_class = "com.gabriel.orders.OrdersApplication",
    boot_launcher_class = "org.springframework.boot.loader.launch.JarLauncher",
    java_library = ":artifact",
)

tar(
    name = "layer",
    srcs = [
        ":uber.jar",
        "@newrelic_java//:newrelic.jar",
    ],
)

oci_image(
    name = "image",
    base = "@amazon_corretto_image",
    entrypoint = [
        "java",
        "-javaagent:orders/newrelic.jar",
        "-jar",
        "-Dspring.profiles.active=prod",
        "orders/uber.jar",
    ],
    tars = [":layer"],
)

oci_push(
    name = "push",
    image = ":image",
    repository = "index.docker.io/gabrielmirandat/orders",
    remote_tags = ["latest"],
)
