FROM amazoncorretto:21
WORKDIR /app
EXPOSE 8001
ADD target/orders*.jar orders.jar
ADD target/newrelic/newrelic.jar newrelic.jar
ADD src/main/resources/newrelic/newrelic.yml newrelic.yml
ENTRYPOINT ["java", "-javaagent:newrelic.jar", "-jar", "orders.jar"]