version: '3.8'
services:
    mongo:
        container_name: postech_mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - postech_network
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: postech_db


    postgres:
        container_name: postech_postgres
        image: postgres:latest
        ports:
            - "5432:5432"
        networks:
            - postech_network
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postech_db

    zookeeper:
        container_name: postech_zookeeper
        image: confluentinc/cp-zookeeper:latest
        networks:
            - postech_network
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        container_name: postech_kafka
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        networks:
            - postech_network
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafdrop:
        container_name: postech_kafdrop
        image: obsidiandynamics/kafdrop:latest
        depends_on:
            - kafka
        ports:
            - "19000:9000"
        networks:
            - postech_network
        environment:
            KAFKA_BROKERCONNECT: kafka:29092

    rabbitmq:
        container_name: postech_rabbitmq
        image: rabbitmq:management
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - postech_network

networks:
    postech_network:
        driver: bridge
