version: '3.8'
services:

  orders-service:
    container_name: postech_orders_service
    build: ./orders
    depends_on:
      - mongo
      - kafka
      - menu-service
    ports:
      - "8001:8001"
    networks:
      - postech_network

  menu-service:
    container_name: postech_menu_service
    build: ./menu
    depends_on:
      - mongo
      - kafka
    ports:
      - "8002:8002"
    networks:
      - postech_network

  mongo:
    container_name: postech_mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummy
      MONGO_INITDB_ROOT_PASSWORD: dummy
      MONGO_INITDB_DATABASE: postech_db
    networks:
      - postech_network

  mongo-express:
    container_name: postech_mongo_express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dummy
      ME_CONFIG_MONGODB_ADMINPASSWORD: dummy
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - postech_network

  redis:
    container_name: postech_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - postech_network

  zookeeper:
    container_name: postech_zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - postech_network

  # TODO: fix to work as like k8s - no need to expose 29092
  kafka:
    container_name: postech_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Map the external port to the internal port
      - "29092:29092" # Map the external port to the internal port
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - postech_network

networks:
  postech_network:
    driver: bridge
