services:

  permissions-service:
    container_name: postech_permissions_service
    #    build: ./opermissions
    image: gabrielmirandat/permissions:latest
    entrypoint: tail -f /dev/null
    depends_on:
      - postgres
      - kafka
    ports:
      - "8000:8000"
    networks:
      - postech_network

  menu-service:
    container_name: postech_menu_service
    #    build: ./menu
    image: gabrielmirandat/menu:latest
    depends_on:
      - mongo
      - kafka
      - permissions-service
    ports:
      - "8002:8002"
    networks:
      - postech_network

  orders-service:
    container_name: postech_orders_service
    #    build: ./orders
    image: gabrielmirandat/orders:latest
    depends_on:
      - mongo
      - kafka
      - permissions-service
      - menu-service
    ports:
      - "8001:8001"
    networks:
      - postech_network

  customers-service:
    container_name: postech_customers_service
    build: ./customers
    depends_on:
      - edgedb
      - kafka
    ports:
      - "8003:8003"
    environment:
      - ENV=docker
    networks:
      - postech_network

  payments-service:
    container_name: postech_payments_service
    build: ./payments
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Cassandra__ContactPoints=cassandra
      - Cassandra__Keyspace=payments
      - Kafka__BootstrapServers=kafka:29092
      - Stripe__ApiKey=${STRIPE_API_KEY:-}
    networks:
      - postech_network

  notifications-service:
    container_name: postech_notifications_service
    build: ./notifications
    depends_on:
      - postgres
      - kafka
    ports:
      - "8005:8005"
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dummy
      - POSTGRES_PASSWORD=dummy
      - POSTGRES_DB=notifications_db
      - KAFKA_SERVER_URL=kafka:29092
      - KAFKA_GROUP_ID=notifications-group-id
      - KAFKA_DOMAIN_TOPIC=orders
      - KAFKA_NOTIFICATIONS_TOPIC=notifications
    networks:
      - postech_network

  cassandra:
    image: cassandra:4.1
    container_name: postech_cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=postech_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_SEEDS=cassandra
    networks:
      - postech_network

  postgres:
    container_name: postech_postgres
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postech_db
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
    networks:
      - postech_network

  mongo:
    container_name: postech_mongo
    image: mongo:6.0.6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dummy
      MONGO_INITDB_ROOT_PASSWORD: dummy
      MONGO_INITDB_DATABASE: postech_db
    networks:
      - postech_network

  edgedb:
    container_name: postech_edgedb
    image: edgedb/edgedb:3.5
    ports:
      - "5656:5656"
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_PASSWORD: dummy
    networks:
      - postech_network

  redis:
    container_name: postech_redis
    image: redis:7.0.13
    ports:
      - "6379:6379"
    networks:
      - postech_network

  zookeeper:
    container_name: postech_zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - postech_network

  kafka:
    container_name: postech_kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - postech_network

networks:
  postech_network:
    driver: bridge
