syntax = "proto3";
option java_multiple_files = true;

package com.gabriel.model;

import "buf/validate/validate.proto";
import "core/model/permission_id.proto";
import "core/model/name.proto";
import "google/protobuf/timestamp.proto";

// Permission: Represents a permission with ID, role, authority, and timestamp
message Permission {
    // PermissionId: Unique identifier for the permission
    PermissionId permission_id = 1;

    // Role name: Name model for the role
    Name role_name = 2;

    // Authority name: Name model for the authority
    Name authority_name = 3;

    // Timestamp: Represents the time the permission was created or updated
    google.protobuf.Timestamp timestamp = 4;
}