# core/BUILD

load("@rules_java//java:defs.bzl", "java_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_java//java:defs.bzl", "java_library")

proto_library(
    name = "menu_proto_deps",
    srcs = ["src/main/java/com/gabriel/specs/menu/menu-api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto"
    ],
)

java_proto_library(
    name = "menu_proto_api_deps",
    visibility = ["//visibility:public"],
    deps = [":menu_proto_deps"],
)

genrule(
    name = "menu_proto_api_jar",
    srcs = [":menu_proto_api_deps"],
    outs = ["menu_proto_api.srcjar"],
    cmd = "cp $(RULEDIR)/menu_proto_deps-speed-src.jar $(location menu_proto_api.srcjar)",
)

java_library(
    name = "menu_proto_api",
    srcs = [":menu_proto_api.srcjar"],
    deps = ["@maven//:com_google_protobuf_protobuf_java"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "permissions_proto_deps",
    srcs = ["src/main/java/com/gabriel/specs/permissions/permissions-api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto"
    ],
)

java_proto_library(
    name = "permissions_proto_api_deps",
    visibility = ["//visibility:public"],
    deps = [":permissions_proto_deps"],
)

genrule(
    name = "permissions_proto_api_jar",
    srcs = [":permissions_proto_api_deps"],
    outs = ["permissions_proto_api.srcjar"],
    cmd = "cp $(RULEDIR)/permissions_proto_deps-speed-src.jar $(location permissions_proto_api.srcjar)",
)

java_library(
    name = "permissions_proto_api",
    srcs = [":permissions_proto_api.srcjar"],
    deps = ["@maven//:com_google_protobuf_protobuf_java"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "artifact",
    visibility = ["//visibility:public"],
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    javacopts = ["-source", "21", "-target", "21"],
    deps = [
        "@maven//:jakarta_validation_jakarta_validation_api",
        "@maven//:jakarta_persistence_jakarta_persistence_api",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
    ],
)

load("@rules_jvm_external//:defs.bzl", "artifact")
load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS", "java_test_suite")

java_test_suite(
    name = "unit",
    srcs = glob(["src/test/unit/java/**/*.java"]),
    runner = "junit5",
    javacopts = ["-source", "21", "-target", "21"],
    resources = glob(["src/test/resources/**"]),
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        "@maven//:org_glassfish_expressly_expressly",
        "@maven//:org_hibernate_validator_hibernate_validator_cdi",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
)