# core/BUILD

load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS", "java_test_suite")
load("@io_grpc_grpc_java//:java_grpc_library.bzl", "java_grpc_library")
load("@rules_java//java:defs.bzl", "java_library", "java_proto_library")
load("@rules_jvm_external//:defs.bzl", "artifact")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "menu_proto",
    srcs = ["src/main/resources/specs/menu-api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
    ],
)

java_proto_library(
    name = "menu_java_proto",
    visibility = ["//visibility:public"],
    deps = [":menu_proto"],
)

java_grpc_library(
    name = "menu_java_grpc",
    srcs = [":menu_proto"],
    visibility = ["//visibility:public"],
    deps = [":menu_java_proto"],
)

proto_library(
    name = "permissions_proto",
    srcs = ["src/main/resources/specs/permissions-api.proto"],
    deps = [
        "@com_google_protobuf//:timestamp_proto",
    ],
)

java_proto_library(
    name = "permissions_java_proto",
    visibility = ["//visibility:public"],
    deps = [":permissions_proto"],
)

java_grpc_library(
    name = "permissions_java_grpc",
    srcs = [":permissions_proto"],
    visibility = ["//visibility:public"],
    deps = [":permissions_java_proto"],
)

java_library(
    name = "artifact",
    srcs = glob(["src/main/java/**/*.java"]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:jakarta_persistence_jakarta_persistence_api",
        "@maven//:jakarta_validation_jakarta_validation_api",
    ],
)

java_test_suite(
    name = "unit",
    srcs = glob(["src/test/unit/java/**/*.java"]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob(["src/test/resources/**"]),
    runner = "junit5",
    runtime_deps = JUNIT5_DEPS,
    deps = [
        ":artifact",
        "@maven//:org_assertj_assertj_core",
        "@maven//:org_glassfish_expressly_expressly",
        "@maven//:org_hibernate_validator_hibernate_validator_cdi",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
    ],
)
