load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "core_lib",
    visibility = ["//visibility:public"],
    srcs = glob(["src/main/java/**/*.java"]),
    javacopts = ["-source", "21", "-target", "21"],
    deps = [
        # Parent dependencies
        "@maven//:io_swagger_core_v3_swagger_annotations",
        "@maven//:org_modelmapper_modelmapper",
        "@maven//:io_cloudevents_cloudevents_core",
        "@maven//:io_cloudevents_cloudevents_kafka",
        "@maven//:io_cloudevents_cloudevents_json_jackson",
        "@maven//:jakarta_validation_jakarta_validation_api",
        "@maven//:jakarta_annotation_jakarta_annotation_api",
        "@maven//:jakarta_persistence_jakarta_persistence_api",
        "@maven//:io_opentelemetry_opentelemetry_api",
        "@maven//:io_opentelemetry_opentelemetry_sdk",
        "@maven//:io_opentelemetry_opentelemetry_exporter_otlp",
        "@maven//:org_yaml_snakeyaml",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_dataformat_jackson_dataformat_yaml",
        "@maven//:com_fasterxml_jackson_module_jackson_module_scala_2_13",

        # Core dependencies
        "@maven//:org_springframework_boot_spring_boot_starter_web",
        "@maven//:org_hibernate_validator_hibernate_validator",
        "@maven//:org_glassfish_expressly_expressly",
        "@maven//:org_hibernate_validator_hibernate_validator_cdi",
        "@maven//:io_grpc_grpc_protobuf",
        "@maven//:io_grpc_grpc_stub",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_google_protobuf_protobuf_java_util",
    ],
)

load("@rules_jvm_external//:defs.bzl", "artifact")
load("@contrib_rules_jvm//java:defs.bzl", "JUNIT5_DEPS", "java_test_suite")

java_test_suite(
    name = "core_test",
    size = "small",
    visibility = ["//visibility:public"],
    srcs = glob(["src/test/java/**/*.java"]),
    runner = "junit5",
    test_suffixes = ["Test.java"],
    runtime_deps = JUNIT5_DEPS,
    javacopts = ["-source", "21", "-target", "21"],
    deps = [
        ":core_lib",
        "@maven//:io_cucumber_cucumber_java",
        "@maven//:io_cucumber_cucumber_junit_platform_engine",
        "@maven//:org_junit_platform_junit_platform_suite",
        "@maven//:org_junit_jupiter_junit_jupiter",
        "@maven//:org_junit_jupiter_junit_jupiter_api",
        "@maven//:org_junit_jupiter_junit_jupiter_engine",
        "@maven//:org_assertj_assertj_core",
        "@maven//:io_rest_assured_rest_assured",
        "@maven//:io_rest_assured_json_path",
        "@maven//:io_rest_assured_json_schema_validator",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_mockito_mockito_junit_jupiter",
    ],
)

load("@rules_java//java:defs.bzl", "java_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "menu_api_proto",
    srcs = ["src/main/java/com/gabriel/specs/menu/menu-api.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:timestamp_proto"
    ],
)

java_proto_library(
    name = "menu_api_java_proto",
    deps = [":menu_api_proto"],
)

proto_library(
    name = "permissions_api_proto",
    srcs = ["src/main/java/com/gabriel/specs/permissions/permissions-api.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:timestamp_proto"
    ],
)

java_proto_library(
    name = "permissions_api_java_proto",
    deps = [":permissions_api_proto"],
)