syntax = "proto3";

package com.gabriel.models;

import "buf/validate/validate.proto";
import "order_id.proto";
import "order_item_id.proto";
import "product_id.proto";
import "ingredient_id.proto";
import "customer_id.proto";
import "permission_id.proto";

message ID {
    oneof with {
        OrderId order_id = 1;
        OrderItemId order_item_id = 2;
        ProductId product_id = 3;
        IngredientId ingredient_id = 4;
        CustomerId customer_id = 5;
        PermissionId permission_id = 6;
    }
}