syntax = "proto3";

option csharp_namespace = "Payments.Api.Protos";

package payments;

service PaymentsService {
  rpc CreatePayment (CreatePaymentRequest) returns (PaymentResponse);
  rpc GetPayment (GetPaymentRequest) returns (PaymentResponse);
}

message CreatePaymentRequest {
  double amount = 1;
  string currency = 2;
  string order_id = 3;
  string customer_id = 4;
  string payment_method_id = 5;
}

message GetPaymentRequest {
  string payment_id = 1;
}

message PaymentResponse {
  string id = 1;
  double amount = 2;
  string currency = 3;
  string order_id = 4;
  string customer_id = 5;
  string status = 6;
  string stripe_payment_intent_id = 7;
  string created_at = 8;
  string processed_at = 9;
}
