#!/bin/sh

echo "Iniciando o OWASP Dependency-Check..."
mvn org.owasp:dependency-check-maven:check

# Verifica o resultado da execução
if [ $? -ne 0 ]; then
  echo "Vulnerability Alert"
  exit 1
fi

echo "None Vulnerabilities"
exit 0