package com.gabriel.menu.integration;

import com.gabriel.menu.core.domain.model.Category;
import com.gabriel.menu.core.domain.model.Ingredient;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Ingredient Domain Integration Tests")
class IngredientDomainIntegrationTest {

    @Test
    @DisplayName("Should create ingredient with valid data")
    void shouldCreateIngredientWithValidData() {
        Ingredient ingredient = new Ingredient(
            "Tomato",
            Category.BURGER,
            2.50,
            0.5,
            false
        );

        assertNotNull(ingredient);
        assertEquals("Tomato", ingredient.getNameString());
        assertEquals(2.50, ingredient.getPriceValue());
        assertEquals(Category.BURGER, ingredient.getCategory());
        assertFalse(ingredient.isExtra());
    }

    @Test
    @DisplayName("Should create ingredient as extra")
    void shouldCreateIngredientAsExtra() {
        Ingredient ingredient = new Ingredient(
            "Extra Cheese",
            Category.BURGER,
            3.00,
            0.3,
            true
        );

        assertNotNull(ingredient);
        assertTrue(ingredient.isExtra());
    }

    // @Test
    // @DisplayName("Should have auto-generated ingredient ID")
    // void shouldHaveAutoGeneratedIngredientId() {
    //     Ingredient ingredient1 = new Ingredient(
    //         "Lettuce",
    //         Category.BURGER,
    //         1.50,
    //         0.2,
    //         false
    //     );
    //
    //     Ingredient ingredient2 = new Ingredient(
    //         "Cheese",
    //         Category.BURGER,
    //         3.00,
    //         0.3,
    //         false
    //     );
    //
    //     assertNotNull(ingredient1.getIngredientID());
    //     assertNotNull(ingredient2.getIngredientID());
    //     assertNotEquals(ingredient1.getIngredientID(), ingredient2.getIngredientID());
    // }

    // @Test
    // @DisplayName("Should have timestamps")
    // void shouldHaveTimestamps() {
    //     Ingredient ingredient = new Ingredient(
    //         "Onion",
    //         Category.BURGER,
    //         1.00,
    //         0.1,
    //         false
    //     );
    //
    //     assertNotNull(ingredient.getCreationTimestamp());
    //     assertNotNull(ingredient.getUpdateTimestamp());
    // }

    @Test
    @DisplayName("Should copy ingredient correctly")
    void shouldCopyIngredientCorrectly() {
        Ingredient original = new Ingredient(
            "Original Ingredient",
            Category.BURGER,
            5.00,
            1.0,
            false
        );

        Ingredient copy = Ingredient.copy(
            original.getIngredientID(),
            original.getName(),
            original.getCategory(),
            original.getPrice(),
            original.getWeight(),
            original.isExtra(),
            original.getCreationTimestamp(),
            original.getUpdateTimestamp()
        );

        assertNotNull(copy);
        assertEquals(original.getIngredientID(), copy.getIngredientID());
        assertEquals(original.getNameString(), copy.getNameString());
        assertEquals(original.getPriceValue(), copy.getPriceValue());
        assertEquals(original.getCategory(), copy.getCategory());
    }

    @Test
    @DisplayName("Should create ingredients with different categories")
    void shouldCreateIngredientsWithDifferentCategories() {
        Ingredient burger = new Ingredient("Beef", Category.BURGER, 5.00, 1.0, false);
        Ingredient dessert = new Ingredient("Chocolate", Category.DESSERT, 3.00, 0.5, false);
        Ingredient drink = new Ingredient("Syrup", Category.DRINK, 2.00, 0.3, false);
        Ingredient accompaniment = new Ingredient("Potato", Category.ACCOMPANIMENT, 1.50, 0.8, false);

        assertEquals(Category.BURGER, burger.getCategory());
        assertEquals(Category.DESSERT, dessert.getCategory());
        assertEquals(Category.DRINK, drink.getCategory());
        assertEquals(Category.ACCOMPANIMENT, accompaniment.getCategory());
    }

    // @Test
    // @DisplayName("Should create ingredients with different prices")
    // void shouldCreateIngredientsWithDifferentPrices() {
    //     Ingredient cheap = new Ingredient("Lettuce", Category.BURGER, 1.00, 0.1, false);
    //     Ingredient medium = new Ingredient("Tomato", Category.BURGER, 2.50, 0.2, false);
    //     Ingredient expensive = new Ingredient("Truffle", Category.BURGER, 50.00, 0.05, true);
    //
    //     assertEquals(1.00, cheap.getPriceValue());
    //     assertEquals(2.50, medium.getPriceValue());
    //     assertEquals(50.00, expensive.getPriceValue());
    // }

    @Test
    @DisplayName("Should have weight property")
    void shouldHaveWeightProperty() {
        Ingredient ingredient = new Ingredient(
            "Cheese",
            Category.BURGER,
            3.50,
            0.3,
            false
        );

        assertNotNull(ingredient.getWeight());
        assertEquals(0.3, ingredient.getWeight().getValue());
    }
}
