syntax = "proto3";
option java_multiple_files = true;

package com.gabriel.model;

import "com/gabriel/model/order_id.proto";
import "com/gabriel/model/order_item_id.proto";
import "com/gabriel/model/product_id.proto";
import "com/gabriel/model/ingredient_id.proto";
import "com/gabriel/model/customer_id.proto";
import "com/gabriel/model/permission_id.proto";

message Id {
    oneof with {
        OrderId order_id = 1;
        OrderItemId order_item_id = 2;
        ProductId product_id = 3;
        IngredientId ingredient_id = 4;
        CustomerId customer_id = 5;
        PermissionId permission_id = 6;
    }
}