# APP
server.port=8000
# POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=dummy
spring.datasource.url=jdbc:postgresql://postgres:5432/postech_db
spring.datasource.username=dummy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# GRPC
grpc.server.port=9000
# AUTHENTICATION
auth0.issuer=${AUTH0_ISSUER:dev-5a5e0c4j3fsshqij.us.auth0.com}
auth0.logout-url=${AUTH0_LOGOUT_URL:http://localhost:8000}
auth0.client-id=${AUTH0_CLIENT_ID}
auth0.client-secret=${AUTH0_CLIENT_SECRET}
auth0.scope=${AUTH0_SCOPE}
auth0.audience=${AUTH0_AUDIENCE}
auth0.app-client-id=${AUTH0_APP_CLIENT_ID}
auth0.app-client-secret=${AUTH0_APP_CLIENT_SECRET}
auth0.app-scope=${AUTH0_APP_SCOPE}
auth0.app-audience=${AUTH0_APP_AUDIENCE}

