# APP
server.port=8000
# POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=dummy
spring.datasource.url=jdbc:postgresql://postgres:5432/postech_db
spring.datasource.username=dummy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# GRPC
grpc.server.port=9000
# AUTHENTICATION
auth0.issuer=${AUTH0_ISSUER:dev-5a5e0c4j3fsshqij.us.auth0.com}
auth0.logout-url=${AUTH0_LOGOUT_URL:http://localhost:8000}
auth0.client-id=${AUTH0_CLIENT_ID:dummy}
auth0.client-secret=${AUTH0_CLIENT_SECRET:dummy}
auth0.scope=${AUTH0_SCOPE:openid profile email}
auth0.audience=${AUTH0_AUDIENCE:https://gabsrell.com}
auth0.application-id=${AUTH0_APPLICATION_ID:dummy}
auth0.application-secret=${AUTH0_APPLICATION_SECRET:dummy}
auth0.application-scope=${AUTH0_APPLICATION_SCOPE:openid profile email}
auth0.application-audience=${AUTH0_APPLICATION_AUDIENCE:https://gabsrell.com}

