# Local development profile
quarkus.log.level=DEBUG
quarkus.log.category."com.gabriel.permissions".level=DEBUG

# PostgreSQL (local)
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postech_db
quarkus.datasource.username=postech
quarkus.datasource.password=postech
