auth0.issuer=${AUTH0_ISSUER:dev-5a5e0c4j3fsshqij.us.auth0.com}
auth0.logout_url=${AUTH0_LOGOUT_URL:http://localhost:8000}
grpc.server.port=9000
server.port=8000
spring.config.import=classpath:permissions.properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=dummy
spring.datasource.url=jdbc:postgresql://postgres:5432/postech_db
spring.datasource.username=dummy
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true