# APP
logging.level.org.springframework.core.env=DEBUG
management.endpoints.web.exposure.include=env,health,info,metrics,prometheus
# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postech_db