# APP (same style as menu)
quarkus.http.port=8000
quarkus.log.level=INFO
quarkus.package.type=uber-jar
quarkus.smallrye-health.liveness-failure-status=503
quarkus.live-reload.enabled=false
quarkus.virtual-threads.enabled=false

# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:dummy}
quarkus.datasource.password=${POSTGRES_PASSWORD:dummy}
quarkus.datasource.jdbc.url=${POSTGRES_JDBC_URL:jdbc:postgresql://postgres:5432/postech_db}
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.hibernate-orm.database.orm-compatibility-mode=false
quarkus.hibernate-orm.log.sql=false

# Liquibase
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.yaml

# gRPC
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=false
quarkus.grpc.server.enable-reflection-service=true
quarkus.log.category."io.grpc".level=DEBUG

# OIDC (JWT) - Auth0
quarkus.oidc.auth-server-url=https://${AUTH0_ISSUER:dev-5a5e0c4j3fsshqij.us.auth0.com}/
quarkus.oidc.client-id=${AUTH0_CLIENT_ID}
quarkus.oidc.credentials.secret=${AUTH0_CLIENT_SECRET}
quarkus.oidc.application-type=service
quarkus.oidc.tls.verification=none
# Roles from JWT claim (custom claim postech_roles is enriched by our augmentor)
quarkus.oidc.roles.role-claim=postech_roles
quarkus.oidc.roles.source=idtoken
quarkus.http.auth.permission.authenticated.paths=/permissions/*,/users/delete-account
quarkus.http.auth.permission.authenticated.policy=authenticated
quarkus.http.auth.permission.public.paths=/users/login,/users/register,/users/logout,/q/health/*
quarkus.http.auth.permission.public.policy=permit

# Custom Auth0 config (for Management API / Unirest)
auth0.issuer=${AUTH0_ISSUER:dev-5a5e0c4j3fsshqij.us.auth0.com}
auth0.logout-url=${AUTH0_LOGOUT_URL:http://localhost:8000}
auth0.client-id=${AUTH0_CLIENT_ID}
auth0.client-secret=${AUTH0_CLIENT_SECRET}
auth0.scope=${AUTH0_SCOPE}
auth0.audience=${AUTH0_AUDIENCE}
auth0.app-client-id=${AUTH0_APP_CLIENT_ID}
auth0.app-client-secret=${AUTH0_APP_CLIENT_SECRET}
auth0.app-scope=${AUTH0_APP_SCOPE}
auth0.app-audience=${AUTH0_APP_AUDIENCE}
