default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  port: <%= ENV.fetch("POSTGRES_PORT") { "5432" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "dummy" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "dummy" } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "notifications_db" } %>

development:
  <<: *default
  database: notifications_db_development

test:
  <<: *default
  database: notifications_db_test

production:
  <<: *default
  database: notifications_db_production
