load("@aspect_bazel_lib//lib:tar.bzl", "tar")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_push")
load("@rules_spring//springboot:springboot.bzl", "springboot")

java_library(
    name = "artifact",
    srcs = glob(["src/main/java/**/*.java"]),
    javacopts = [
        "-source",
        "21",
        "-target",
        "21",
    ],
    resources = glob(["src/main/resources/**"]),
    visibility = ["//visibility:public"],
    deps = [
        "//core:artifact",
        "//core:permissions_java_grpc",
        "//core:permissions_java_proto",
        "@maven//:com_auth0_auth0_spring_security_api",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_fasterxml_jackson_core_jackson_core",
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_google_protobuf_protobuf_java",
        "@maven//:com_konghq_unirest_java_core",
        "@maven//:com_konghq_unirest_modules_jackson",
        "@maven//:io_grpc_grpc_api",
        "@maven//:io_grpc_grpc_netty_shaded",
        "@maven//:io_grpc_grpc_protobuf",
        "@maven//:io_grpc_grpc_stub",
        "@maven//:io_micrometer_micrometer_core",
        "@maven//:io_micrometer_micrometer_tracing_bridge_brave",
        "@maven//:jakarta_persistence_jakarta_persistence_api",
        "@maven//:jakarta_transaction_jakarta_transaction_api",
        "@maven//:net_devh_grpc_server_spring_boot_starter",
        "@maven//:net_devh_grpc_spring_boot_starter",
        "@maven//:org_apache_tomcat_annotations_api",
        "@maven//:org_apache_tomcat_embed_tomcat_embed_core",
        "@maven//:org_hibernate_orm_hibernate_core",
        "@maven//:org_liquibase_liquibase_core",
        "@maven//:org_postgresql_postgresql",
        "@maven//:org_springframework_boot_spring_boot",
        "@maven//:org_springframework_boot_spring_boot_autoconfigure",
        "@maven//:org_springframework_boot_spring_boot_starter_data_jpa",
        "@maven//:org_springframework_boot_spring_boot_starter_security",
        "@maven//:org_springframework_boot_spring_boot_starter_web",
        "@maven//:org_springframework_data_spring_data_jpa",
        "@maven//:org_springframework_security_spring_security_config",
        "@maven//:org_springframework_security_spring_security_core",
        "@maven//:org_springframework_security_spring_security_oauth2_jose",
        "@maven//:org_springframework_security_spring_security_oauth2_resource_server",
        "@maven//:org_springframework_security_spring_security_web",
        "@maven//:org_springframework_spring_beans",
        "@maven//:org_springframework_spring_context",
        "@maven//:org_springframework_spring_core",
        "@maven//:org_springframework_spring_tx",
        "@maven//:org_springframework_spring_web",
    ],
)

#java_binary(
#    name = "uber",
#    main_class = "com.gabriel.permissions.PermissionsApplication",
#    runtime_deps = [":artifact"],
#)

springboot(
    name = "uber",
    boot_app_class = "com.gabriel.permissions.PermissionsApplication",
    boot_launcher_class = "org.springframework.boot.loader.launch.JarLauncher",
    java_library = ":artifact",
    visibility = ["//visibility:public"],
)

tar(
    name = "layer",
    srcs = [
        ":uber.jar",
    ],
)

oci_image(
    name = "image",
    base = "@amazon_corretto_image",
    entrypoint = [
        "java",
        "-jar",
        "-Dspring.profiles.active=prod",
        "permissions/uber.jar",
    ],
    tars = [":layer"],
)

oci_push(
    name = "push",
    image = ":image",
    remote_tags = ["latest"],
    repository = "index.docker.io/gabrielmirandat/permissions",
)
