/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `kotlin-dsl`
    java
    idea
    id("io.quarkus") version "3.9.2"
    id("org.openapi.generator") version "7.0.1"
}

group = "com.gabriel"
version = "1.0.0-SNAPSHOT"
description = "Menu API"

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets {
    main {
        java {
            srcDirs("src/main/java", "$buildDir/generated/src/gen/java")
        }
    }
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
    api(libs.io.swagger.core.v3.swagger.annotations)
    api(libs.org.modelmapper.modelmapper)
    api(libs.io.cloudevents.cloudevents.core)
    api(libs.io.cloudevents.cloudevents.kafka)
    api(libs.io.cloudevents.cloudevents.json.jackson)
    api(libs.jakarta.validation.jakarta.validation.api)
    api(libs.jakarta.annotation.jakarta.annotation.api)
    api(libs.jakarta.persistence.jakarta.persistence.api)
    api(libs.io.opentelemetry.opentelemetry.api)
    api(libs.io.opentelemetry.opentelemetry.sdk)
    api(libs.io.opentelemetry.opentelemetry.exporter.otlp)
    api(libs.org.yaml.snakeyaml)
    api(libs.com.fasterxml.jackson.core.jackson.core)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.fasterxml.jackson.core.jackson.annotations)
    api(libs.com.fasterxml.jackson.dataformat.jackson.dataformat.yaml)
    api(libs.com.fasterxml.jackson.module.jackson.module.scala.v2.v13)
    api(libs.com.gabriel.core)
    api(libs.io.quarkus.quarkus.resteasy)
    api(libs.io.quarkus.quarkus.hibernate.validator)
    api(libs.io.quarkus.quarkus.resteasy.jackson)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jsr310)
    api(libs.io.quarkus.quarkus.mongodb.client)
    api(libs.io.mongock.mongock.standalone)
    api(libs.io.mongock.mongodb.sync.v4.driver)
    api(libs.io.quarkus.quarkus.messaging.kafka)
    api(libs.javax.annotation.javax.annotation.api)
    api(libs.com.google.protobuf.protobuf.java)
    api(libs.io.quarkus.quarkus.grpc)
    api(libs.io.quarkus.quarkus.smallrye.health)
    api(libs.io.grpc.grpc.api)
    api(libs.io.grpc.grpc.services)
    api(libs.io.grpc.grpc.protobuf)
    api(libs.io.grpc.grpc.stub)
    testImplementation(libs.io.cucumber.cucumber.java)
    testImplementation(libs.io.cucumber.cucumber.junit.platform.engine)
    testImplementation(libs.org.junit.platform.junit.platform.suite)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.api)
    testImplementation(libs.org.junit.jupiter.junit.jupiter.engine)
    testImplementation(libs.org.assertj.assertj.core)
    testImplementation(libs.io.rest.assured.rest.assured)
    testImplementation(libs.io.rest.assured.json.path)
    testImplementation(libs.io.rest.assured.json.schema.validator)
    testImplementation(libs.org.mockito.mockito.core)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.testcontainers.testcontainers)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    testImplementation(libs.io.quarkus.quarkus.junit5)
}

openApiGenerate {
    generatorName.set("jaxrs-spec")
    inputSpec.set("$rootDir/src/main/resources/oas/menu-api.yaml")
    outputDir.set("$buildDir/generated")
    apiPackage.set("com.gabriel.specs.menu")
    modelPackage.set("com.gabriel.specs.menu.models")
    configOptions.set(
        mapOf(
            "openApiNullable" to "false",
            "interfaceOnly" to "true",
            "useBeanValidation" to "true",
            "useOptional" to "true",
            "library" to "quarkus",
            "useJakartaEe" to "true",
            "useSwaggerAnnotations" to "false"
        )
    )
    skipValidateSpec.set(false)
}

configurations.all {
    resolutionStrategy {
        force("com.google.protobuf:protobuf-java:4.28.2")
        force("com.google.protobuf:protobuf-java-util:4.28.2")
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.named("compileJava") {
    dependsOn("openApiGenerate")
}

tasks.withType<Test> {
    dependsOn(":quarkusBuild")
    dependsOn(":openApiGenerate")
    useJUnitPlatform()
}