syntax = "proto3";
option java_multiple_files = true;
option java_outer_classname = "MenuProtoClient";
package com.gabriel.service.menu;

import "google/protobuf/timestamp.proto";

// gRPC service
service Menu {
  rpc RetrieveMenu (MenuRequest) returns (MenuResponse);
}

// Request message with category filter option
message MenuRequest {
  string category = 1;
}

// Defining an individual menu item
message MenuItem {
  string id = 1;
  string name = 2;
  double price = 3;
  string category = 4;
  google.protobuf.Timestamp lastUpdated = 5;
}

// Response message
message MenuResponse {
  repeated MenuItem items = 1;
}
