syntax = "proto3";
option java_multiple_files = true;
option java_outer_classname = "PermissionProtoClient";
package com.gabriel.service.permissions;

import "google/protobuf/timestamp.proto";

// gRPC service for Permissions
service Permission {
  rpc RetrievePermissions (PermissionRequest) returns (PermissionResponse);
}

// Request message (possibly to filter by specific role)
message PermissionRequest {
  string role = 1; // Optional, if you want to filter by a specific role
}

// Defining the association between role and authorities
message PermissionItem {
  string id = 1;
  string role = 2;
  string authority = 3;
  google.protobuf.Timestamp lastUpdated = 4;
}

// Response message containing a list of role associations with their permissions
message PermissionResponse {
  repeated PermissionItem items = 1;
}
