name: Flow to deploy production artifact

on:
  push:
    branches:
     - feature**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Protocol Buffers Compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Check protoc version
        run: protoc --version
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package -Dmaven.test.skip=true
      - name: Upload orders-api artifact
        uses: actions/upload-artifact@v2
        with:
          name: orders-artifact
          path: |
            ./orders/target/orders*.jar
            ./orders/target/newrelic/newrelic.jar
            ./orders/src/main/resources/newrelic/newrelic.yml
      - name: Upload menu-api artifact
        uses: actions/upload-artifact@v2
        with:
          name: menu-artifact
          path: ./menu/target/menu*.jar
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"
      - name: Download orders-api artifact
        uses: actions/download-artifact@v2
        with:
          name: orders-artifact
          path: ./temp/orders
      - name: Reorganize orders-api files
        run: |
          find ./temp/orders -type f -exec printf '%s\n' {} \;
          mkdir -p ./orders/target/newrelic
          mkdir -p ./orders/src/main/resources/newrelic
          mv ./temp/orders/target/newrelic/newrelic.jar ./orders/target/newrelic/newrelic.jar
          mv ./temp/orders/src/main/resources/newrelic/newrelic.yml ./orders/src/main/resources/newrelic/newrelic.yml
          mv ./temp/orders/target/orders-0.0.1-SNAPSHOT.jar ./orders/target/
      - name: Download menu-api artifact
        uses: actions/download-artifact@v2
        with:
          name: menu-artifact
          path: ./menu/target
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        run: |
          TAGGED_VERSION="v${{ github.run_number }}-${{ steps.short-sha.outputs.sha }}"
          TAGGED_COMMIT_SHA=${{ github.sha }}
          TAGGED_VERSION_URL="https://github.com/${{ github.repository }}/releases/tag/$TAGGED_VERSION"
          TAGGED_COMMIT_URL="https://github.com/${{ github.repository }}/commit/$TAGGED_COMMIT_SHA"
          
          echo "TAGGED_VERSION=$TAGGED_VERSION" >> $GITHUB_ENV
          echo "TAGGED_COMMIT_SHA=$TAGGED_COMMIT_SHA" >> $GITHUB_ENV
          echo "TAGGED_VERSION_URL=$TAGGED_VERSION_URL" >> $GITHUB_ENV
          echo "TAGGED_COMMIT_URL=$TAGGED_COMMIT_URL" >> $GITHUB_ENV
          
          docker build -t gabrielmirandat/postech-fiap-tc-orders-api:$TAGGED_VERSION ./orders
          docker push gabrielmirandat/postech-fiap-tc-orders-api:$TAGGED_VERSION
          docker build -t gabrielmirandat/postech-fiap-tc-menu-api:$TAGGED_VERSION ./menu
          docker push gabrielmirandat/postech-fiap-tc-menu-api:$TAGGED_VERSION

  tag:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create and push tag
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git tag -a ${{ env.TAGGED_VERSION }} -m "Deploying version ${{ env.TAGGED_VERSION }}. Details: ${{ env.TAGGED_COMMIT_URL }}"
          git push origin ${{ env.TAGGED_VERSION }}
  

  notify:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: "A build ${{ github.run_number }} foi concluída com sucesso! Confira os detalhes no commit: ${{ env.TAGGED_COMMIT_URL }}. Veja a tag da versão: ${{ env.TAGGED_VERSION_URL }}"


#  deploy:
#    needs: tag
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Terraform
#        uses: hashicorp/setup-terraform@v1
#        with:
#          terraform_version: 1.0.0
#      - name: Terraform Init
#        run: terraform init
#      - name: Terraform Apply
#       run: terraform apply -auto-approve
#      - name: Update Kubernetes deployment
#        run: |
#          kubectl set image deployment/orders-api orders-api=gabrielmirandat/orders-api:${{ github.sha }} --record
#          kubectl set image deployment/menu-api menu-api=gabrielmirandat/menu-api:${{ github.sha }} --record
