name: Pull Request Flow

on:
  pull_request:
    branches:
      - develop

env:
  TF_LOG: DEBUG
  TF_DIR: ".terraform/"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Bazelisk
        run: |
          if [ ! -f ~/.bazelisk/bazelisk ]; then
            mkdir -p ~/.bazelisk
            curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o ~/.bazelisk/bazelisk
            chmod +x ~/.bazelisk/bazelisk
          fi
          sudo ln -sf ~/.bazelisk/bazelisk /usr/local/bin/bazel
      - name: Verify Bazel version
        run: bazel version
      - name: Install Protocol Buffers Compiler 4.28.2
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://github.com/protocolbuffers/protobuf/releases/download/v28.2/protoc-28.2-linux-x86_64.zip
          unzip protoc-28.2-linux-x86_64.zip -d protoc-28.2
          sudo mv protoc-28.2/bin/protoc /usr/local/bin/
          sudo mv protoc-28.2/include/* /usr/local/include/
      - name: Check protoc version
        run: protoc --version
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Bazel
        run: bazel build //...

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Bazel build output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            bazel-bin
            bazel-out
          key: bazel-build-${{ runner.os }}-${{ hashFiles('WORKSPACE', 'BUILD.bazel') }}
          restore-keys: bazel-build-${{ runner.os }}
      - name: Test with Bazel
        run: bazel test $(bazel query 'filter(":unit", //...:*)')

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Bazel build output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            bazel-bin
            bazel-out
          key: bazel-build-${{ runner.os }}-${{ hashFiles('WORKSPACE', 'BUILD.bazel') }}
          restore-keys: bazel-build-${{ runner.os }}
      - name: Test with Bazel
        run: bazel test $(bazel query 'filter(":integration", //...:*)')

  behavior-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Bazel build output
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel
            bazel-bin
            bazel-out
          key: bazel-build-${{ runner.os }}-${{ hashFiles('WORKSPACE', 'BUILD.bazel') }}
          restore-keys: bazel-build-${{ runner.os }}
      - name: Test with Bazel
        run: bazel test $(bazel query 'filter(":behavior", //...:*)')

  terraform-validate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup to run Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Format Terraform files
        id: fmt
        run: terraform fmt -check
        working-directory: ${{ env.TF_DIR }}
      - name: Init configuration
        id: init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}
      - name: Validate Terraform script
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.TF_DIR }}