name: Test actions

on:
  push:
    branches:
      - feature**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update API versions
        run: |
          ORDERS_REPOSITORY="gabrielmirandat/postech-fiap-tc-orders-api"
          MENU_REPOSITORY="gabrielmirandat/postech-fiap-tc-menu-api"
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
          
          sed -i 's|<ORDERS_API_IMAGE>|'"$ORDERS_REPOSITORY:$GEN_VERSION"'|g' .k8s/orders-api-deployment.yaml
          sed -i 's|<MENU_API_IMAGE>|'"$MENU_REPOSITORY:$GEN_VERSION"'|g' .k8s/menu-api-deployment.yaml
          
          cat .k8s/orders-api-deployment.yaml
          cat .k8s/menu-api-deployment.yaml
  notify-deploy:
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare Success Message
        if: ${{ needs.deploy.result == 'success' }}
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          TAG_URL="https://github.com/${{ github.repository }}/releases/tag/$GEN_VERSION"  
          echo "DISCORD_ARGS=O deploy ${{ github.run_number }} foi concluído com sucesso! Confira os detalhes no commit: $COMMIT_URL. Veja a tag da versão: $TAG_URL" >> $GITHUB_ENV
      - name: Prepare Failure Message
        if: ${{ needs.deploy.result == 'failure' }}
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          GEN_VERSION="v${{ github.run_number }}-$SHORT_SHA"
          WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "DISCORD_ARGS=O deploy $GEN_VERSION falhou. Confira os detalhes: $WORKFLOW_URL." >> $GITHUB_ENV
      - name: Notify Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
          args: ${{ env.DISCORD_ARGS }}